name: CI

on: [push]

jobs:
  build:
    runs-on: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.11
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: org.example.impl.updatesite
          path: org.example.impl.updatesite/target/org.example.impl.updatesite-*.zip

  doc:
    runs-on: [ubuntu-22.04]
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.11
      - name: Create JavaDoc with Maven
        run: mvn --batch-mode --update-snapshots site
      - name: Upload doc artifact
        uses: actions/upload-artifact@v4
        with:
          name: javadoc
          path: org.example.impl/target/site

  test:
    runs-on: [ubuntu-22.04]
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.11
      - name: Test with Maven
        run: mvn --batch-mode --update-snapshots clean verify
